psql_app_name: psql-location-service
application_name: "location-service"

postgresql_pv_capacity: 5Gi 
postgresql_version: 12-el8
postgresql_is_namespace: openshift
postgresql_service_account: "{{ psql_app_name }}"
psql_user_name: dbuser
psql_user_passwd: password
psql_db_name: sampledb
psql_credentials_secret: "{{ psql_app_name }}"
postgresql_max_prepared_transactions: 100
postgresql_max_connections: 100
postgresql_init_configmap: "{{ psql_app_name }}-init"
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m
psql_init_scripts:
undeploy_app_db: false

service_account: "{{ application_name }}"
application_properties: application.properties
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"
binary_imagestream_template: binary-imagestream.yml 
service_image: quay.io/jbride/fuse-location-service
service_image_tag: 0.0.1
application_template: app-service.yml
app_java_max_mem_ratio: 60
app_java_initial_mem_ratio: 0
app_gc_max_metaspace_size: 500
